import { NextRequest, NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';
import { getDb } from '@/lib/firebase-admin';
import { getMenu, type MenuItem } from '@/lib/menu';

export const dynamic = 'force-dynamic';

type Answers = {
  flavor?: string;
  temperature?: string;
  sweetness?: string;
  intensity?: string;
};

type Suggestion = { name: string; emoji: string; reason: string };

// --- BEGIN AI-GENERATED CODE ---
// Some or all of the code below was generated by AI.
// Source: GitHub Copilot
// Model Used: GPT-5.4
// Human reviewed and approved on 2026-06-17 by Author
function scoreItem(item: MenuItem, answers: Answers) {
  let score = 0;
  const tags = new Set(item.tags);

  if (answers.flavor?.includes('fruity') && (tags.has('fruity') || tags.has('refreshing'))) score += 3;
  if (answers.flavor?.includes('creamy') && (tags.has('creamy') || tags.has('rich'))) score += 3;
  if (answers.flavor?.includes('herbal') && (tags.has('herbal') || tags.has('earthy'))) score += 3;
  if (answers.flavor?.includes('classic') && tags.has('classic')) score += 3;

  if (answers.temperature?.includes('cold') && tags.has('cold')) score += 2;
  if (answers.temperature?.includes('hot') && tags.has('hot')) score += 2;
  if (answers.temperature === 'warm' && tags.has('hot')) score += 1;

  if (answers.sweetness?.includes('quite sweet') && tags.has('sweet')) score += 2;
  if (answers.sweetness?.includes('lightly sweet') && tags.has('lightly-sweet')) score += 2;
  if (answers.sweetness?.includes('not sweet') && tags.has('not-sweet')) score += 2;

  if (answers.intensity?.includes('bold') && (tags.has('bold') || tags.has('rich'))) score += 2;
  if (answers.intensity?.includes('light') && tags.has('light')) score += 2;
  if (answers.intensity?.includes('balanced')) score += 1;

  return score;
}

function buildFallbackReason(item: MenuItem, answers: Answers) {
  const flavorLead = answers.flavor?.includes('fruity')
    ? 'Its bright, fruit-forward profile fits the fresh flavors you picked.'
    : answers.flavor?.includes('creamy')
      ? 'Its smooth, creamy texture lines up well with the richer style you chose.'
      : answers.flavor?.includes('herbal')
        ? 'Its mellow herbal notes match the earthy direction you went for.'
        : 'Its familiar cafe profile makes it an easy match for your taste.';

  const finish = answers.temperature?.includes('cold')
    ? 'Served chilled, it should feel especially refreshing.'
    : answers.temperature?.includes('hot') || answers.temperature === 'warm'
      ? 'Served warm, it should feel comforting and satisfying.'
      : 'It should land nicely for the mood you described.';

  return `${flavorLead} ${finish}`;
}

function getFallbackSuggestions(menu: MenuItem[], answers: Answers): Suggestion[] {
  return [...menu]
    .map((item) => ({ item, score: scoreItem(item, answers) }))
    .sort((left, right) => right.score - left.score)
    .slice(0, 2)
    .map(({ item }) => ({
      name: item.name,
      emoji: item.emoji,
      reason: buildFallbackReason(item, answers),
    }));
}
// --- END AI-GENERATED CODE ---

export async function POST(req: NextRequest) {
  // --- BEGIN AI-GENERATED CODE ---
  // Some or all of the code below was generated by AI.
  // Source: GitHub Copilot
  // Model Used: Claude Sonnet 4.6
  // Human reviewed and approved on 2026-06-17 by Author
  // Instantiated inside the handler (not at module level) so the Anthropic SDK
  // is never evaluated during Next.js build-time page-data collection.
  const anthropic = new Anthropic();
  // --- END AI-GENERATED CODE ---
  try {
    const { answers, tableId } = await req.json();
    const menu = getMenu();

    const menuText = menu
      .map((item) => `• ${item.emoji} ${item.name} — ${item.description}`)
      .join('\n');

    let suggestions: Suggestion[];

    try {
      const msg = await anthropic.messages.create({
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 512,
        messages: [
          {
            role: 'user',
            content: `You are a warm, friendly barista helping a customer pick the perfect drink.

Customer taste profile:
- Flavor: ${answers.flavor}
- Temperature: ${answers.temperature}
- Sweetness: ${answers.sweetness}
- Intensity: ${answers.intensity}

Our menu:
${menuText}

Suggest exactly 2 items that best match this customer. Write a short, personal reason for each (1–2 warm sentences).

Reply with ONLY valid JSON — no markdown, no explanation:
[{"name":"...","emoji":"...","reason":"..."},{"name":"...","emoji":"...","reason":"..."}]`,
          },
        ],
      });

      const raw = msg.content[0].type === 'text' ? msg.content[0].text.trim() : '[]';

      try {
        suggestions = JSON.parse(raw);
      } catch {
        const stripped = raw.replace(/^```[^\n]*\n?/, '').replace(/\n?```$/, '').trim();
        suggestions = JSON.parse(stripped);
      }
    } catch (error) {
      console.warn('[/api/suggest] Falling back to local matching', error);
      suggestions = getFallbackSuggestions(menu, answers);
    }

    const db = getDb();
    const ref = db.collection('sessions').doc();
    await ref.set({
      tableId: tableId ?? null,
      answers,
      suggestions,
      createdAt: new Date(),
      rating: null,
      comment: null,
      reviewedAt: null,
    });

    return NextResponse.json({ sessionId: ref.id, suggestions });
  } catch (err) {
    console.error('[/api/suggest]', err);
    return NextResponse.json({ error: 'Failed to get suggestions' }, { status: 500 });
  }
}
