// --- BEGIN AI-GENERATED CODE ---
// Some or all of the code below was generated by AI.
// Source: GitHub Copilot
// Model Used: Claude Sonnet 4.6
// Human reviewed and approved on 2026-06-17 by Author
import type { Firestore } from 'firebase-admin/firestore';

// Cached Firestore instance — lazy-loaded on first request so that
// firebase-admin is never imported at build time (avoids Next.js
// "Collecting page data" phase failures caused by JSON.parse of env vars).
let _db: Firestore | null = null;

export function getDb(): Firestore {
  if (_db) return _db;

  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { initializeApp, getApps, cert } = require('firebase-admin/app') as typeof import('firebase-admin/app');
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { getFirestore } = require('firebase-admin/firestore') as typeof import('firebase-admin/firestore');

  if (!getApps().length) {
    const key = process.env.FIREBASE_SERVICE_ACCOUNT_KEY;
    if (!key) throw new Error('FIREBASE_SERVICE_ACCOUNT_KEY is not set');
    initializeApp({ credential: cert(JSON.parse(key)) });
  }
  _db = getFirestore();
  return _db;
}
// --- END AI-GENERATED CODE ---
