import { NextRequest, NextResponse } from 'next/server';
import { getDb } from '@/lib/firebase-admin';
import { Resend } from 'resend';

export const dynamic = 'force-dynamic';

export async function POST(req: NextRequest) {
  try {
    // --- BEGIN AI-GENERATED CODE ---
    // Some or all of the code below was generated by AI.
    // Source: GitHub Copilot
    // Model Used: GPT-5.3-Codex
    // Human reviewed and approved on 2026-06-17 by Author
    const { sessionId, rating, comment, menuSuggestion } = await req.json();
    const db = getDb();
    await db.collection('sessions').doc(sessionId).update({
      rating: rating ?? null,
      comment: comment || null,
      menuSuggestion: menuSuggestion || null,
      reviewedAt: new Date(),
    });

    const resendKey = process.env.RESEND_API_KEY;
    const toEmail = process.env.FEEDBACK_TO_EMAIL;
    const fromEmail = process.env.FEEDBACK_FROM_EMAIL;

    if (resendKey && toEmail && fromEmail) {
      const resend = new Resend(resendKey);
      const safeRating = typeof rating === 'number' ? rating : null;
      const safeComment = typeof comment === 'string' ? comment.trim() : '';
      const safeSuggestion = typeof menuSuggestion === 'string' ? menuSuggestion.trim() : '';

      await resend.emails.send({
        from: fromEmail,
        to: toEmail,
        subject: `New customer feedback (${sessionId})`,
        html: `
          <h2>New customer feedback</h2>
          <p><strong>Session ID:</strong> ${sessionId}</p>
          <p><strong>Rating:</strong> ${safeRating ?? 'Not provided'}</p>
          <p><strong>Review:</strong><br/>${safeComment || 'Not provided'}</p>
          <p><strong>Menu suggestion:</strong><br/>${safeSuggestion || 'Not provided'}</p>
          <p><em>Sent at: ${new Date().toISOString()}</em></p>
        `,
      });
    } else {
      console.warn('[/api/review] Email not sent: missing RESEND_API_KEY, FEEDBACK_TO_EMAIL, or FEEDBACK_FROM_EMAIL');
    }
    // --- END AI-GENERATED CODE ---

    return NextResponse.json({ ok: true });
  } catch (err) {
    console.error('[/api/review]', err);
    return NextResponse.json({ error: 'Failed to save review' }, { status: 500 });
  }
}
